name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8

    - name: Lint with flake8
      run: |
        # Run flake8 to check for code style and quality issues
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Run flake8 to check for other style issues without failing the build
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run the FastAPI server
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8000